# generated by datamodel-codegen:
#   filename:  manifest_v7.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, ConfigDict, Field, constr

from dbt_artifacts_parser.parsers.base import BaseParserModel


class ManifestMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dbt_schema_version: str | None = "https://schemas.getdbt.com/dbt/manifest/v7.json"
    dbt_version: str | None = "1.3.0b2"
    generated_at: AwareDatetime | None = "2022-09-14T20:35:15.346636Z"
    invocation_id: str | None = "c59a8269-533c-4b78-a709-5094045afd4d"
    env: dict[str, str] | None = {}
    project_id: str | None = Field(
        None, description="A unique identifier for the project"
    )
    user_id: (
        constr(pattern=r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
        | None
    ) = Field(None, description="A unique identifier for the user")
    send_anonymous_usage_stats: bool | None = Field(
        None, description="Whether dbt is configured to send anonymous usage statistics"
    )
    adapter_type: str | None = Field(None, description="The type name of the adapter")


class ResourceType(Enum):
    analysis = "analysis"


class FileHash(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    checksum: str


class Hook(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sql: str
    transaction: bool | None = True
    index: int | None = None


class Docs(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    show: bool | None = True
    node_color: str | None = None


class DependsOn(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    macros: list[str] | None = []
    nodes: list[str] | None = []


class ColumnInfo(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    description: str | None = ""
    meta: dict[str, Any] | None = {}
    data_type: str | None = None
    quote: bool | None = None
    tags: list[str] | None = []


class InjectedCTE(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    sql: str


class ResourceType1(Enum):
    test = "test"


class TestConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field("dbt_test__audit", alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    materialized: str | None = "test"
    severity: constr(pattern=r"^([Ww][Aa][Rr][Nn]|[Ee][Rr][Rr][Oo][Rr])$") | None = (
        "ERROR"
    )
    store_failures: bool | None = None
    where: str | None = None
    limit: int | None = None
    fail_calc: str | None = "count(*)"
    warn_if: str | None = "!= 0"
    error_if: str | None = "!= 0"


class ResourceType2(Enum):
    model = "model"


class ResourceType3(Enum):
    operation = "operation"


class ResourceType4(Enum):
    rpc = "rpc"


class ResourceType5(Enum):
    sql_operation = "sql operation"


class ResourceType6(Enum):
    test = "test"


class TestMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    kwargs: dict[str, Any] | None = {}
    namespace: str | None = None


class ResourceType7(Enum):
    seed = "seed"


class SeedConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field(None, alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    materialized: str | None = "seed"
    incremental_strategy: str | None = None
    persist_docs: dict[str, Any] | None = {}
    post_hook: list[Hook] | None = Field([], alias="post-hook", validate_default=True)
    pre_hook: list[Hook] | None = Field([], alias="pre-hook", validate_default=True)
    quoting: dict[str, Any] | None = {}
    column_types: dict[str, Any] | None = {}
    full_refresh: bool | None = None
    unique_key: str | list[str] | None = None
    on_schema_change: str | None = "ignore"
    grants: dict[str, Any] | None = {}
    packages: list[str] | None = []
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    quote_columns: bool | None = None


class ResourceType8(Enum):
    snapshot = "snapshot"


class ResourceType9(Enum):
    analysis = "analysis"


class ResourceType10(Enum):
    test = "test"


class ParsedSingularTestNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType10
    alias: str
    checksum: FileHash
    config: TestConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": "dbt_test__audit",
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "test",
            "severity": "ERROR",
            "store_failures": None,
            "where": None,
            "limit": None,
            "fail_calc": "count(*)",
            "warn_if": "!= 0",
            "error_if": "!= 0",
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.370925
    config_call_dict: dict[str, Any] | None = {}


class ResourceType11(Enum):
    operation = "operation"


class ResourceType12(Enum):
    model = "model"


class ResourceType13(Enum):
    rpc = "rpc"


class ResourceType14(Enum):
    sql_operation = "sql operation"


class ResourceType15(Enum):
    test = "test"


class ParsedGenericTestNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    test_metadata: TestMetadata
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType15
    alias: str
    checksum: FileHash
    config: TestConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": "dbt_test__audit",
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "test",
            "severity": "ERROR",
            "store_failures": None,
            "where": None,
            "limit": None,
            "fail_calc": "count(*)",
            "warn_if": "!= 0",
            "error_if": "!= 0",
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.3784761
    config_call_dict: dict[str, Any] | None = {}
    column_name: str | None = None
    file_key_name: str | None = None


class ResourceType16(Enum):
    seed = "seed"


class ParsedSeedNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType16
    alias: str
    checksum: FileHash
    config: SeedConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "seed",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "quote_columns": None,
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.380325
    config_call_dict: dict[str, Any] | None = {}


class ResourceType17(Enum):
    snapshot = "snapshot"


class SnapshotConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field(None, alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    materialized: str | None = "snapshot"
    incremental_strategy: str | None = None
    persist_docs: dict[str, Any] | None = {}
    post_hook: list[Hook] | None = Field([], alias="post-hook", validate_default=True)
    pre_hook: list[Hook] | None = Field([], alias="pre-hook", validate_default=True)
    quoting: dict[str, Any] | None = {}
    column_types: dict[str, Any] | None = {}
    full_refresh: bool | None = None
    unique_key: str | None = None
    on_schema_change: str | None = "ignore"
    grants: dict[str, Any] | None = {}
    packages: list[str] | None = []
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    strategy: str | None = None
    target_schema: str | None = None
    target_database: str | None = None
    updated_at: str | None = None
    check_cols: str | list[str] | None = None


class ResourceType18(Enum):
    source = "source"


class Quoting(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: bool | None = None
    schema_: bool | None = Field(None, alias="schema")
    identifier: bool | None = None
    column: bool | None = None


class FreshnessMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dbt_schema_version: str | None = "https://schemas.getdbt.com/dbt/sources/v3.json"
    dbt_version: str | None = "1.3.0b2"
    generated_at: AwareDatetime | None = "2022-09-14T20:35:15.341700Z"
    invocation_id: str | None = "c59a8269-533c-4b78-a709-5094045afd4d"
    env: dict[str, str] | None = {}


class Status(Enum):
    runtime_error = "runtime error"


class SourceFreshnessRuntimeError(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    error: str | int | None = None
    status: Status


class Status1(Enum):
    pass_ = "pass"
    warn = "warn"
    error = "error"
    runtime_error = "runtime error"


class Period(Enum):
    minute = "minute"
    hour = "hour"
    day = "day"


class Time(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int | None = None
    period: Period | None = None


class TimingInfo(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class ExternalPartition(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = ""
    description: str | None = ""
    data_type: str | None = ""
    meta: dict[str, Any] | None = {}


class SourceConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True


class ResourceType19(Enum):
    macro = "macro"


class SupportedLanguage(Enum):
    python = "python"
    sql = "sql"


class MacroDependsOn(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    macros: list[str] | None = []


class MacroArgument(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: str | None = None
    description: str | None = ""


class ParsedDocumentation(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    block_contents: str


class Type(Enum):
    dashboard = "dashboard"
    notebook = "notebook"
    analysis = "analysis"
    ml = "ml"
    application = "application"


class ResourceType20(Enum):
    model = "model"
    analysis = "analysis"
    test = "test"
    snapshot = "snapshot"
    operation = "operation"
    seed = "seed"
    rpc = "rpc"
    sql_operation = "sql operation"
    docs_block = "docs block"
    source = "source"
    macro = "macro"
    exposure = "exposure"
    metric = "metric"


class Maturity(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class ExposureOwner(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str
    name: str | None = None


class ExposureConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True


class MetricFilter(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    operator: str
    value: str


class Period1(Enum):
    day = "day"
    week = "week"
    month = "month"
    year = "year"


class MetricTime(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int | None = None
    period: Period1 | None = None


class MetricConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True


class NodeConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field(None, alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    materialized: str | None = "view"
    incremental_strategy: str | None = None
    persist_docs: dict[str, Any] | None = {}
    post_hook: list[Hook] | None = Field([], alias="post-hook", validate_default=True)
    pre_hook: list[Hook] | None = Field([], alias="pre-hook", validate_default=True)
    quoting: dict[str, Any] | None = {}
    column_types: dict[str, Any] | None = {}
    full_refresh: bool | None = None
    unique_key: str | list[str] | None = None
    on_schema_change: str | None = "ignore"
    grants: dict[str, Any] | None = {}
    packages: list[str] | None = []
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)


class CompiledSingularTestNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType1
    alias: str
    checksum: FileHash
    config: TestConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": "dbt_test__audit",
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "test",
            "severity": "ERROR",
            "store_failures": None,
            "where": None,
            "limit": None,
            "fail_calc": "count(*)",
            "warn_if": "!= 0",
            "error_if": "!= 0",
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.35441
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class CompiledModelNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType2
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.356541
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class CompiledHookNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType3
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.3582149
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None
    index: int | None = None


class CompiledRPCNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType4
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.359935
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class CompiledSqlNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType5
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.361423
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class CompiledGenericTestNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    test_metadata: TestMetadata
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType6
    alias: str
    checksum: FileHash
    config: TestConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": "dbt_test__audit",
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "test",
            "severity": "ERROR",
            "store_failures": None,
            "where": None,
            "limit": None,
            "fail_calc": "count(*)",
            "warn_if": "!= 0",
            "error_if": "!= 0",
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.363411
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None
    column_name: str | None = None
    file_key_name: str | None = None


class CompiledSeedNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType7
    alias: str
    checksum: FileHash
    config: SeedConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "seed",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "quote_columns": None,
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.366584
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class CompiledSnapshotNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType8
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.3682182
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class ParsedAnalysisNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType9
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.369675
    config_call_dict: dict[str, Any] | None = {}


class ParsedHookNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType11
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.372257
    config_call_dict: dict[str, Any] | None = {}
    index: int | None = None


class ParsedModelNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType12
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.373705
    config_call_dict: dict[str, Any] | None = {}


class ParsedRPCNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType13
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.375131
    config_call_dict: dict[str, Any] | None = {}


class ParsedSqlNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType14
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.376405
    config_call_dict: dict[str, Any] | None = {}


class ParsedSnapshotNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType17
    alias: str
    checksum: FileHash
    config: SnapshotConfig
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.3832462
    config_call_dict: dict[str, Any] | None = {}


class FreshnessThreshold(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    warn_after: Time | None = Field(
        {"count": None, "period": None}, validate_default=True
    )
    error_after: Time | None = Field(
        {"count": None, "period": None}, validate_default=True
    )
    filter: str | None = None


class SourceFreshnessOutput(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    max_loaded_at: AwareDatetime
    snapshotted_at: AwareDatetime
    max_loaded_at_time_ago_in_s: float
    status: Status1
    criteria: FreshnessThreshold
    adapter_response: dict[str, Any]
    timing: list[TimingInfo]
    thread_id: str
    execution_time: float


class ExternalTable(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    location: str | None = None
    file_format: str | None = None
    row_format: str | None = None
    tbl_properties: str | None = None
    partitions: list[ExternalPartition] | None = None


class ParsedMacro(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    macro_sql: str
    resource_type: ResourceType19
    tags: list[str] | None = []
    depends_on: MacroDependsOn | None = Field({"macros": []}, validate_default=True)
    description: str | None = ""
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    arguments: list[MacroArgument] | None = Field([], validate_default=True)
    created_at: float | None = 1663187715.386226
    supported_languages: list[SupportedLanguage] | None = None


class ParsedExposure(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fqn: list[str]
    unique_id: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    type: Type
    owner: ExposureOwner
    resource_type: ResourceType20 | None = "exposure"
    description: str | None = ""
    label: str | None = None
    maturity: Maturity | None = None
    meta: dict[str, Any] | None = {}
    tags: list[str] | None = []
    config: ExposureConfig | None = Field({"enabled": True}, validate_default=True)
    unrendered_config: dict[str, Any] | None = {}
    url: str | None = None
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    created_at: float | None = 1663187715.3878772


class ParsedMetric(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fqn: list[str]
    unique_id: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    description: str
    label: str
    calculation_method: str
    expression: str
    timestamp: str | None = None
    filters: list[MetricFilter]
    time_grains: list[str]
    dimensions: list[str]
    window: MetricTime | None = None
    model: str | None = None
    model_unique_id: str | None = None
    resource_type: ResourceType20 | None = "metric"
    meta: dict[str, Any] | None = {}
    tags: list[str] | None = []
    config: MetricConfig | None = Field({"enabled": True}, validate_default=True)
    unrendered_config: dict[str, Any] | None = {}
    sources: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    refs: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    created_at: float | None = 1663187715.38939


class CompiledAnalysisNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compiled: bool
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    fqn: list[str]
    unique_id: str
    raw_code: str
    language: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    resource_type: ResourceType
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    refs: list[list[str]] | None = []
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    compiled_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1663187715.3517282
    config_call_dict: dict[str, Any] | None = {}
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    relation_name: str | None = None


class ParsedSourceDefinition(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fqn: list[str]
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    unique_id: str
    package_name: str
    root_path: str
    path: str
    original_file_path: str
    name: str
    source_name: str
    source_description: str
    loader: str
    identifier: str
    resource_type: ResourceType18
    quoting: Quoting | None = Field(
        {"database": None, "schema": None, "identifier": None, "column": None},
        validate_default=True,
    )
    loaded_at_field: str | None = None
    freshness: FreshnessThreshold | None = None
    external: ExternalTable | None = None
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    source_meta: dict[str, Any] | None = {}
    tags: list[str] | None = []
    config: SourceConfig | None = Field({"enabled": True}, validate_default=True)
    patch_path: str | None = None
    unrendered_config: dict[str, Any] | None = {}
    relation_name: str | None = None
    created_at: float | None = 1663187715.3854342


class ManifestV7(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata: ManifestMetadata = Field(..., description="Metadata about the manifest")
    nodes: dict[
        str,
        CompiledAnalysisNode
        | CompiledSingularTestNode
        | CompiledModelNode
        | CompiledHookNode
        | CompiledRPCNode
        | CompiledSqlNode
        | CompiledGenericTestNode
        | CompiledSeedNode
        | CompiledSnapshotNode
        | ParsedAnalysisNode
        | ParsedSingularTestNode
        | ParsedHookNode
        | ParsedModelNode
        | ParsedRPCNode
        | ParsedSqlNode
        | ParsedGenericTestNode
        | ParsedSeedNode
        | ParsedSnapshotNode,
    ] = Field(
        ..., description="The nodes defined in the dbt project and its dependencies"
    )
    sources: dict[str, ParsedSourceDefinition] = Field(
        ..., description="The sources defined in the dbt project and its dependencies"
    )
    macros: dict[str, ParsedMacro] = Field(
        ..., description="The macros defined in the dbt project and its dependencies"
    )
    docs: dict[str, ParsedDocumentation] = Field(
        ..., description="The docs defined in the dbt project and its dependencies"
    )
    exposures: dict[str, ParsedExposure] = Field(
        ..., description="The exposures defined in the dbt project and its dependencies"
    )
    metrics: dict[str, ParsedMetric] = Field(
        ..., description="The metrics defined in the dbt project and its dependencies"
    )
    selectors: dict[str, Any] = Field(
        ..., description="The selectors defined in selectors.yml"
    )
    disabled: (
        dict[
            str,
            list[
                CompiledAnalysisNode
                | CompiledSingularTestNode
                | CompiledModelNode
                | CompiledHookNode
                | CompiledRPCNode
                | CompiledSqlNode
                | CompiledGenericTestNode
                | CompiledSeedNode
                | CompiledSnapshotNode
                | ParsedAnalysisNode
                | ParsedSingularTestNode
                | ParsedHookNode
                | ParsedModelNode
                | ParsedRPCNode
                | ParsedSqlNode
                | ParsedGenericTestNode
                | ParsedSeedNode
                | ParsedSnapshotNode
                | ParsedSourceDefinition
            ],
        ]
        | None
    ) = Field(None, description="A mapping of the disabled nodes in the target")
    parent_map: dict[str, list[str]] | None = Field(
        None, description="A mapping from\xa0child nodes to their dependencies"
    )
    child_map: dict[str, list[str]] | None = Field(
        None, description="A mapping from parent nodes to their dependents"
    )
