# generated by datamodel-codegen:
#   filename:  manifest_v9.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, ConfigDict, Field, constr

from dbt_artifacts_parser.parsers.base import BaseParserModel


class ManifestMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dbt_schema_version: str | None = "https://schemas.getdbt.com/dbt/manifest/v9.json"
    dbt_version: str | None = "1.5.0b5"
    generated_at: AwareDatetime | None = "2023-04-12T03:35:01.188035Z"
    invocation_id: str | None = "8aa1596d-f52f-40bc-ad4b-f5e48fc7e6c2"
    env: dict[str, str] | None = {}
    project_id: str | None = Field(
        None, description="A unique identifier for the project"
    )
    user_id: (
        constr(pattern=r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
        | None
    ) = Field(None, description="A unique identifier for the user")
    send_anonymous_usage_stats: bool | None = Field(
        None, description="Whether dbt is configured to send anonymous usage statistics"
    )
    adapter_type: str | None = Field(None, description="The type name of the adapter")


class ResourceType(Enum):
    analysis = "analysis"


class FileHash(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    checksum: str


class Hook(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sql: str
    transaction: bool | None = True
    index: int | None = None


class Docs(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    show: bool | None = True
    node_color: str | None = None


class ContractConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enforced: bool | None = False


class Type(Enum):
    check = "check"
    not_null = "not_null"
    unique = "unique"
    primary_key = "primary_key"
    foreign_key = "foreign_key"
    custom = "custom"


class ColumnLevelConstraint(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    name: str | None = None
    expression: str | None = None
    warn_unenforced: bool | None = True
    warn_unsupported: bool | None = True


class RefArgs(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    package: str | None = None
    version: str | float | None = None


class DependsOn(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    macros: list[str] | None = []
    nodes: list[str] | None = []


class InjectedCTE(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    sql: str


class Contract(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enforced: bool | None = False
    checksum: str | None = None


class ResourceType1(Enum):
    test = "test"


class TestConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field("dbt_test__audit", alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    group: str | None = None
    materialized: str | None = "test"
    severity: constr(pattern=r"^([Ww][Aa][Rr][Nn]|[Ee][Rr][Rr][Oo][Rr])$") | None = (
        "ERROR"
    )
    store_failures: bool | None = None
    where: str | None = None
    limit: int | None = None
    fail_calc: str | None = "count(*)"
    warn_if: str | None = "!= 0"
    error_if: str | None = "!= 0"


class ResourceType2(Enum):
    operation = "operation"


class ResourceType3(Enum):
    model = "model"


class Access(Enum):
    protected = "protected"
    private = "private"
    public = "public"


class ModelLevelConstraint(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    name: str | None = None
    expression: str | None = None
    warn_unenforced: bool | None = True
    warn_unsupported: bool | None = True
    columns: list[str] | None = []


class ResourceType4(Enum):
    rpc = "rpc"


class ResourceType5(Enum):
    sql_operation = "sql operation"


class ResourceType6(Enum):
    test = "test"


class TestMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    kwargs: dict[str, Any] | None = {}
    namespace: str | None = None


class ResourceType7(Enum):
    snapshot = "snapshot"


class SnapshotConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field(None, alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    group: str | None = None
    materialized: str | None = "snapshot"
    incremental_strategy: str | None = None
    persist_docs: dict[str, Any] | None = {}
    post_hook: list[Hook] | None = Field([], alias="post-hook", validate_default=True)
    pre_hook: list[Hook] | None = Field([], alias="pre-hook", validate_default=True)
    quoting: dict[str, Any] | None = {}
    column_types: dict[str, Any] | None = {}
    full_refresh: bool | None = None
    unique_key: str | None = None
    on_schema_change: str | None = "ignore"
    grants: dict[str, Any] | None = {}
    packages: list[str] | None = []
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    contract: ContractConfig | None = Field({"enforced": False}, validate_default=True)
    strategy: str | None = None
    target_schema: str | None = None
    target_database: str | None = None
    updated_at: str | None = None
    check_cols: str | list[str] | None = None


class ResourceType8(Enum):
    seed = "seed"


class SeedConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field(None, alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    group: str | None = None
    materialized: str | None = "seed"
    incremental_strategy: str | None = None
    persist_docs: dict[str, Any] | None = {}
    post_hook: list[Hook] | None = Field([], alias="post-hook", validate_default=True)
    pre_hook: list[Hook] | None = Field([], alias="pre-hook", validate_default=True)
    quoting: dict[str, Any] | None = {}
    column_types: dict[str, Any] | None = {}
    full_refresh: bool | None = None
    unique_key: str | list[str] | None = None
    on_schema_change: str | None = "ignore"
    grants: dict[str, Any] | None = {}
    packages: list[str] | None = []
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    contract: ContractConfig | None = Field({"enforced": False}, validate_default=True)
    quote_columns: bool | None = None


class MacroDependsOn(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    macros: list[str] | None = []


class ResourceType9(Enum):
    source = "source"


class Quoting(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: bool | None = None
    schema_: bool | None = Field(None, alias="schema")
    identifier: bool | None = None
    column: bool | None = None


class FreshnessMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dbt_schema_version: str | None = "https://schemas.getdbt.com/dbt/sources/v3.json"
    dbt_version: str | None = "1.5.0b5"
    generated_at: AwareDatetime | None = "2023-04-12T03:35:01.185979Z"
    invocation_id: str | None = "8aa1596d-f52f-40bc-ad4b-f5e48fc7e6c2"
    env: dict[str, str] | None = {}


class Status(Enum):
    runtime_error = "runtime error"


class SourceFreshnessRuntimeError(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    error: str | int | None = None
    status: Status


class Status1(Enum):
    pass_ = "pass"
    warn = "warn"
    error = "error"
    runtime_error = "runtime error"


class Period(Enum):
    minute = "minute"
    hour = "hour"
    day = "day"


class Time(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int | None = None
    period: Period | None = None


class TimingInfo(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class ExternalPartition(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = ""
    description: str | None = ""
    data_type: str | None = ""
    meta: dict[str, Any] | None = {}


class SourceConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True


class ResourceType10(Enum):
    macro = "macro"


class SupportedLanguage(Enum):
    python = "python"
    sql = "sql"


class MacroArgument(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: str | None = None
    description: str | None = ""


class ResourceType11(Enum):
    doc = "doc"


class Documentation(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    resource_type: ResourceType11
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    block_contents: str


class ResourceType12(Enum):
    exposure = "exposure"


class Type2(Enum):
    dashboard = "dashboard"
    notebook = "notebook"
    analysis = "analysis"
    ml = "ml"
    application = "application"


class Maturity(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class Owner(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    email: str | None = None
    name: str | None = None


class ExposureConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True


class ResourceType13(Enum):
    metric = "metric"


class MetricFilter(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    operator: str
    value: str


class Period1(Enum):
    day = "day"
    week = "week"
    month = "month"
    year = "year"


class MetricTime(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int | None = None
    period: Period1 | None = None


class MetricConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    group: str | None = None


class ResourceType14(Enum):
    group = "group"


class Group(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    resource_type: ResourceType14
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    owner: Owner


class NodeConfig(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    alias: str | None = None
    schema_: str | None = Field(None, alias="schema")
    database: str | None = None
    tags: list[str] | str | None = []
    meta: dict[str, Any] | None = {}
    group: str | None = None
    materialized: str | None = "view"
    incremental_strategy: str | None = None
    persist_docs: dict[str, Any] | None = {}
    post_hook: list[Hook] | None = Field([], alias="post-hook", validate_default=True)
    pre_hook: list[Hook] | None = Field([], alias="pre-hook", validate_default=True)
    quoting: dict[str, Any] | None = {}
    column_types: dict[str, Any] | None = {}
    full_refresh: bool | None = None
    unique_key: str | list[str] | None = None
    on_schema_change: str | None = "ignore"
    grants: dict[str, Any] | None = {}
    packages: list[str] | None = []
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    contract: ContractConfig | None = Field({"enforced": False}, validate_default=True)


class ColumnInfo(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    description: str | None = ""
    meta: dict[str, Any] | None = {}
    data_type: str | None = None
    constraints: list[ColumnLevelConstraint] | None = Field([], validate_default=True)
    quote: bool | None = None
    tags: list[str] | None = []


class SingularTestNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType1
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: TestConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": "dbt_test__audit",
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "test",
            "severity": "ERROR",
            "store_failures": None,
            "where": None,
            "limit": None,
            "fail_calc": "count(*)",
            "warn_if": "!= 0",
            "error_if": "!= 0",
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.19095
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )


class HookNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType2
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "contract": {"enforced": False},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.191555
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )
    index: int | None = None


class ModelNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType3
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "contract": {"enforced": False},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.192162
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )
    access: Access | None = "protected"
    constraints: list[ModelLevelConstraint] | None = Field([], validate_default=True)
    version: str | float | None = None
    latest_version: str | float | None = None


class RPCNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType4
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "contract": {"enforced": False},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.192949
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )


class SqlNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType5
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "contract": {"enforced": False},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.1935291
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )


class GenericTestNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    test_metadata: TestMetadata
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType6
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: TestConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": "dbt_test__audit",
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "test",
            "severity": "ERROR",
            "store_failures": None,
            "where": None,
            "limit": None,
            "fail_calc": "count(*)",
            "warn_if": "!= 0",
            "error_if": "!= 0",
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.19419
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )
    column_name: str | None = None
    file_key_name: str | None = None
    attached_node: str | None = None


class SnapshotNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType7
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: SnapshotConfig
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.1952698
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )


class SeedNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType8
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: SeedConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "seed",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "contract": {"enforced": False},
            "quote_columns": None,
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.1968079
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    root_path: str | None = None
    depends_on: MacroDependsOn | None = Field({"macros": []}, validate_default=True)


class FreshnessThreshold(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    warn_after: Time | None = Field(
        {"count": None, "period": None}, validate_default=True
    )
    error_after: Time | None = Field(
        {"count": None, "period": None}, validate_default=True
    )
    filter: str | None = None


class SourceFreshnessOutput(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    max_loaded_at: AwareDatetime
    snapshotted_at: AwareDatetime
    max_loaded_at_time_ago_in_s: float
    status: Status1
    criteria: FreshnessThreshold
    adapter_response: dict[str, Any]
    timing: list[TimingInfo]
    thread_id: str
    execution_time: float


class ExternalTable(BaseParserModel):
    model_config = ConfigDict(
        extra="allow",
    )
    location: str | None = None
    file_format: str | None = None
    row_format: str | None = None
    tbl_properties: str | None = None
    partitions: list[str] | list[ExternalPartition] | None = None


class Macro(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    resource_type: ResourceType10
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    macro_sql: str
    depends_on: MacroDependsOn | None = Field({"macros": []}, validate_default=True)
    description: str | None = ""
    meta: dict[str, Any] | None = {}
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    arguments: list[MacroArgument] | None = Field([], validate_default=True)
    created_at: float | None = 1681270501.198105
    supported_languages: list[SupportedLanguage] | None = None


class Exposure(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    resource_type: ResourceType12
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    type: Type2
    owner: Owner
    description: str | None = ""
    label: str | None = None
    maturity: Maturity | None = None
    meta: dict[str, Any] | None = {}
    tags: list[str] | None = []
    config: ExposureConfig | None = Field({"enabled": True}, validate_default=True)
    unrendered_config: dict[str, Any] | None = {}
    url: str | None = None
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    created_at: float | None = 1681270501.198782


class Metric(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    resource_type: ResourceType13
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    description: str
    label: str
    calculation_method: str
    expression: str
    filters: list[MetricFilter]
    time_grains: list[str]
    dimensions: list[str]
    timestamp: str | None = None
    window: MetricTime | None = None
    model: str | None = None
    model_unique_id: str | None = None
    meta: dict[str, Any] | None = {}
    tags: list[str] | None = []
    config: MetricConfig | None = Field(
        {"enabled": True, "group": None}, validate_default=True
    )
    unrendered_config: dict[str, Any] | None = {}
    sources: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    refs: list[RefArgs] | None = Field([], validate_default=True)
    metrics: list[list[str]] | None = []
    created_at: float | None = 1681270501.199492
    group: str | None = None


class AnalysisNode(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    alias: str
    checksum: FileHash
    config: NodeConfig | None = Field(
        {
            "enabled": True,
            "alias": None,
            "schema": None,
            "database": None,
            "tags": [],
            "meta": {},
            "group": None,
            "materialized": "view",
            "incremental_strategy": None,
            "persist_docs": {},
            "quoting": {},
            "column_types": {},
            "full_refresh": None,
            "unique_key": None,
            "on_schema_change": "ignore",
            "grants": {},
            "packages": [],
            "docs": {"show": True, "node_color": None},
            "contract": {"enforced": False},
            "post-hook": [],
            "pre-hook": [],
        },
        validate_default=True,
    )
    tags: list[str] | None = []
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    group: str | None = None
    docs: Docs | None = Field({"show": True, "node_color": None}, validate_default=True)
    patch_path: str | None = None
    build_path: str | None = None
    deferred: bool | None = False
    unrendered_config: dict[str, Any] | None = {}
    created_at: float | None = 1681270501.189703
    config_call_dict: dict[str, Any] | None = {}
    relation_name: str | None = None
    raw_code: str | None = ""
    language: str | None = "sql"
    refs: list[RefArgs] | None = Field([], validate_default=True)
    sources: list[list[str]] | None = []
    metrics: list[list[str]] | None = []
    depends_on: DependsOn | None = Field(
        {"macros": [], "nodes": []}, validate_default=True
    )
    compiled_path: str | None = None
    compiled: bool | None = False
    compiled_code: str | None = None
    extra_ctes_injected: bool | None = False
    extra_ctes: list[InjectedCTE] | None = Field([], validate_default=True)
    contract: Contract | None = Field(
        {"enforced": False, "checksum": None}, validate_default=True
    )


class SourceDefinition(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    database: str | None = None
    schema_: str = Field(..., alias="schema")
    name: str
    resource_type: ResourceType9
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: list[str]
    source_name: str
    source_description: str
    loader: str
    identifier: str
    quoting: Quoting | None = Field(
        {"database": None, "schema": None, "identifier": None, "column": None},
        validate_default=True,
    )
    loaded_at_field: str | None = None
    freshness: FreshnessThreshold | None = None
    external: ExternalTable | None = None
    description: str | None = ""
    columns: dict[str, ColumnInfo] | None = Field({}, validate_default=True)
    meta: dict[str, Any] | None = {}
    source_meta: dict[str, Any] | None = {}
    tags: list[str] | None = []
    config: SourceConfig | None = Field({"enabled": True}, validate_default=True)
    patch_path: str | None = None
    unrendered_config: dict[str, Any] | None = {}
    relation_name: str | None = None
    created_at: float | None = 1681270501.197819


class ManifestV9(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata: ManifestMetadata = Field(..., description="Metadata about the manifest")
    nodes: dict[
        str,
        AnalysisNode
        | SingularTestNode
        | HookNode
        | ModelNode
        | RPCNode
        | SqlNode
        | GenericTestNode
        | SnapshotNode
        | SeedNode,
    ] = Field(
        ..., description="The nodes defined in the dbt project and its dependencies"
    )
    sources: dict[str, SourceDefinition] = Field(
        ..., description="The sources defined in the dbt project and its dependencies"
    )
    macros: dict[str, Macro] = Field(
        ..., description="The macros defined in the dbt project and its dependencies"
    )
    docs: dict[str, Documentation] = Field(
        ..., description="The docs defined in the dbt project and its dependencies"
    )
    exposures: dict[str, Exposure] = Field(
        ..., description="The exposures defined in the dbt project and its dependencies"
    )
    metrics: dict[str, Metric] = Field(
        ..., description="The metrics defined in the dbt project and its dependencies"
    )
    groups: dict[str, Group] = Field(
        ..., description="The groups defined in the dbt project"
    )
    selectors: dict[str, Any] = Field(
        ..., description="The selectors defined in selectors.yml"
    )
    disabled: (
        dict[
            str,
            list[
                AnalysisNode
                | SingularTestNode
                | HookNode
                | ModelNode
                | RPCNode
                | SqlNode
                | GenericTestNode
                | SnapshotNode
                | SeedNode
                | SourceDefinition
                | Exposure
                | Metric
            ],
        ]
        | None
    ) = Field(None, description="A mapping of the disabled nodes in the target")
    parent_map: dict[str, list[str]] | None = Field(
        None, description="A mapping from\xa0child nodes to their dependencies"
    )
    child_map: dict[str, list[str]] | None = Field(
        None, description="A mapping from parent nodes to their dependents"
    )
    group_map: dict[str, list[str]] | None = Field(
        None, description="A mapping from group names to their nodes"
    )
