# generated by datamodel-codegen:
#   filename:  sources_v3.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field

from dbt_artifacts_parser.parsers.base import BaseParserModel


class Metadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dbt_schema_version: str | None = None
    dbt_version: str | None = "1.12.0a1"
    generated_at: str | None = None
    invocation_id: str | None = None
    invocation_started_at: str | None = None
    env: dict[str, str] | None = None


class Status(Enum):
    runtime_error = "runtime error"


class Results(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    error: str | int | None
    status: Status


class Status1(Enum):
    pass_ = "pass"
    warn = "warn"
    error = "error"
    runtime_error = "runtime error"


class Period(Enum):
    minute = "minute"
    hour = "hour"
    day = "day"


class WarnAfter(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int | None = None
    period: Period | None = None


class ErrorAfter(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int | None = None
    period: Period | None = None


class Criteria(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    warn_after: WarnAfter | None = None
    error_after: ErrorAfter | None = None
    filter: str | None = None


class TimingItem(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    started_at: str | None = None
    completed_at: str | None = None


class Results1(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    max_loaded_at: str
    snapshotted_at: str
    max_loaded_at_time_ago_in_s: float
    status: Status1
    criteria: Criteria = Field(..., title="FreshnessThreshold")
    adapter_response: dict[str, Any]
    timing: list[TimingItem]
    thread_id: str
    execution_time: float


class SourcesV3(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata: Metadata = Field(..., title="FreshnessMetadata")
    results: list[Results | Results1]
    elapsed_time: float
