# generated by datamodel-codegen:
#   filename:  sources_v2.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, ConfigDict

from dbt_artifacts_parser.parsers.base import BaseParserModel


class FreshnessMetadata(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dbt_schema_version: str | None = "https://schemas.getdbt.com/dbt/sources/v2.json"
    dbt_version: str | None = "0.21.0rc1"
    generated_at: AwareDatetime | None = "2021-09-24T13:29:14.312598Z"
    invocation_id: str | None = None
    env: dict[str, str] | None = {}


class Status(Enum):
    runtime_error = "runtime error"


class SourceFreshnessRuntimeError(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    error: str | int | None = None
    status: Status


class Status1(Enum):
    pass_ = "pass"
    warn = "warn"
    error = "error"
    runtime_error = "runtime error"


class Period(Enum):
    minute = "minute"
    hour = "hour"
    day = "day"


class Time(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int
    period: Period


class TimingInfo(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class FreshnessThreshold(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    warn_after: Time | None = None
    error_after: Time | None = None
    filter: str | None = None


class SourceFreshnessOutput(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unique_id: str
    max_loaded_at: AwareDatetime
    snapshotted_at: AwareDatetime
    max_loaded_at_time_ago_in_s: float
    status: Status1
    criteria: FreshnessThreshold
    adapter_response: dict[str, Any]
    timing: list[TimingInfo]
    thread_id: str
    execution_time: float


class SourcesV2(BaseParserModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata: FreshnessMetadata
    results: list[SourceFreshnessRuntimeError | SourceFreshnessOutput]
    elapsed_time: float
